---
- name: Configure k3s vip
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - haproxy
    - server
    - agent
  roles:
    - haproxy

- name: Complete k3s prereqs
  hosts: k3s
  gather_facts: true
  become: true
  tags:
    - prereq
    - server
    - agent
  roles:
    - k3s-prereq

- name: Bootstrap k3s cluster
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - init-managers
    - server
    - agent
  roles:
    - k3s-server

- name: Extract k3s join token
  hosts: k3s_managers
  gather_facts: false
  become: true
  tags:
    - init-workers
    - agent
  tasks:
    - name: Fetch k3s token file
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/agent-token
        dest: .secret/{{ cluster_name }}/agent-token
        flat: true

- name: Join k3s - workers
  hosts: k3s_workers
  gather_facts: true
  become: true
  tags:
    - init-workers
    - agent
  vars:
    k3s_agent_token: "{{ lookup('file', '.secret/' + cluster_name + '/agent-token') | trim() }}"
  roles:
    - k3s-agent

- name: Delete k3s join token
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - init-workers
    - agent
  tasks:
    - name: Remove k3s token file
      ansible.builtin.file:
        path: .secret/{{ cluster_name }}/agent-token
        state: absent

- name: Validate Nodes joined cluster
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - init-workers
    - agent
  tasks:
    - name: Verify that all server nodes joined
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/kubectl get nodes -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (managers | length + role_labels | length)
      retries: 20
      delay: 10
      changed_when: false

- name: Apply cluster configurations
  hosts: k3s_managers
  gather_facts: true
  become: true
  run_once: true
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
    K8S_AUTH_NO_PROXY: "{{ no_proxy }}"
  tags:
    - cluster-config
    - server
    - agent
  roles:
    - k3s-config

- name: Install Helm
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - helm
    - server
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
    K8S_AUTH_NO_PROXY: "{{ no_proxy }}"
  roles:
    - helm
