---
- name: Uninstall docker
  hosts:
    - lab
  tasks:
    - name: Set static ip
      when: static_ip is defined
      ansible.builtin.copy:
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              {{ ethernet.device }}:
                dhcp4: false
                addresses:
                  - "{{ static_ip }}/{{ network.subnet | split('/') | last }}"
                routes:
                  - to: default
                    via: "{{ network.gateway }}"
                nameservers:
                  addresses:
                    - "{{ network.dns1 }}"
                    - "{{ network.dns2 }}"
                    - 1.1.1.1
                    - 1.0.0.1
        dest: /etc/netplan/99-nodecfg.yaml
      register: netplan
    - name: Apply netplan
      ansible.builtin.shell: netplan apply
      when: netplan.changed