---
- name: Uninstall docker
  hosts:
    - raspberry
  tasks:
    - name: uninstall pip dependencies
      become: yes
      ansible.builtin.pip:
        name: 
          - docker
          - pyyaml
          - requests
          - jsondiff
        state: absent

    - name: Stop docker service
      become: yes
      ansible.builtin.systemd:
        name: docker
        state: stopped

    - name: Remove docker
      become: yes
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - python3-pip
        state: absent

    - name: Remove docker directories
      become: yes
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/docker
        - /var/lib/docker
        - /var/run/docker.sock
        - /var/run/docker.pid
        - /var/run/docker
        - /var/log/docker

    - name: Remove docker group
      become: yes
      ansible.builtin.group:
        name: docker
        state: absent

    - name: Remove docker apt repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch={{ 'arm64' if 'pi' in ansible_hostname else 'amd64' }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: absent

    - name: Remove docker GPG apt key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: absent