---
- name: Reset k3s
  hosts: k3s
  gather_facts: true
  become: true
  tasks:
    - name: Cleanup Cilium
      ansible.builtin.command: |
        ip link del cilium_host
        ip link del cilium_net
        ip link del cilium_vxlan
        iptables-save | grep -v cilium | iptables-restore
        ip6tables-save | grep -v cilium | ip6tables-restore
      failed_when: false
      changed_when: false

    - name: Uninstall k3s
      when:
        - "'k3s_managers' in group_names"
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-uninstall.sh
        removes: /usr/local/bin/k3s-uninstall.sh
      failed_when: false

    - name: Uninstall k3s agent
      when: "'k3s_workers' in group_names"
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-agent-uninstall.sh agent --uninstall
        removes: /usr/local/bin/k3s-agent-uninstall.sh
      failed_when: false

    - name: Remove k3s data
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
      failed_when: false

    - name: Get longhorn directory sub-paths
      ansible.builtin.find:
        paths: /var/lib/longhorn
        hidden: true
        recurse: true
        file_type: any
      register: collected_files

    - name: Cleanup longhorn directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ collected_files }}"
