---
- name: Configure k3s vip
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - haproxy
    - server
    - agent
  roles:
    - haproxy

- name: Complete k3s prereqs
  hosts: k3s
  gather_facts: true
  become: true
  tags:
    - prereq
    - server
    - agent
  roles:
    - k3s-prereq

- name: Bootstrap k3s cluster
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - init-managers
    - server
    - agent
  roles:
    - k3s-server

- name: Join k3s - workers
  hosts: k3s_workers
  gather_facts: true
  become: true
  tags:
    - init-workers
    - agent
  roles:
    - k3s-agent

- name: Remove k3s token files from servers
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - init-workers
    - init-managers
    - server
    - agent
  tasks:
    - name: Remove k3s agent token file
      ansible.builtin.file:
        path: "{{ k3s_agent_token_file }}"
        state: absent

- name: Validate Nodes joined cluster
  hosts: k3s_managers
  gather_facts: true
  become: true
  tags:
    - init-workers
    - agent
  tasks:
    - name: Verify that all server nodes joined
      ansible.builtin.command:
        cmd: >
          k3s kubectl get nodes -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (managers | length + role_labels | length)
      retries: 20
      delay: 10
      changed_when: false

- name: Apply cluster configurations
  hosts: k3s_managers
  gather_facts: true
  become: true
  run_once: true
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  tags:
    - cluster-config
    - server
    - agent
  roles:
    - k3s-config
