---
- name: Configure k3s vip
  hosts: 
    - k3s_managers
    - test-k3s-managers
  gather_facts: true
  become: true
  tags:
    - haproxy
    - server
    - agent
  roles:
    - haproxy

- name: Complete k3s prereqs
  hosts: 
    - k3s
    - test-k3s
  gather_facts: true
  become: true
  tags:
    - install
    - server
    - agent
    - prereq
  roles:
    - k3s-prereq

- name: Initialize k3s servers
  hosts: 
    - k3s_managers
    - test-k3s-managers
  gather_facts: true
  become: true
  tags:
    - server
    - agent
    - install
    - config
    - server-install
  roles:
    - k3s-server

- name: Join k3s - workers
  hosts: 
    - k3s_workers
    - test-k3s-workers
  gather_facts: true
  become: true
  tags:
    - agent
    - install
    - config
    - join-workers
  roles:
    - k3s-agent

# FIXME: This only supports one cluster
# - name: Label nodes
#   hosts: 
#     - k3s_managers
#     - test-k3s-managers
#   gather_facts: true
#   become: true
#   run_once: true
#   environment:
#     KUBECONFIG: "{{ kube_config_path }}"
#   tags:
#     - server
#     - agent
#     - config
#   tasks:
#     - name: Label nodes
#       # no_log: true
#       kubernetes.core.k8s:
#         state: present
#         definition:
#           apiVersion: v1
#           kind: Node
#           metadata:
#             labels:
#               kubernetes.io/role: "{{ item.role }}"
#         name: "{{ item.name }}"
#       with_items:
#         - name: keylimepi
#           role: worker
#         - name: pumpkinpi
#           role: worker
#         - name: raspberrypi
#           role: infra
#         - name: vwkr01
#           role: worker
#         - name: wkr02vl
#           role: worker
#         - name: gmr01pl
#           role: gamer
#         - name: gmr02vl
#           role: gamer

- name: Restrict kube-system pods to managers
  hosts: 
    - k3s_managers
    - test-k3s-managers
  gather_facts: true
  become: true
  run_once: true
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  tags:
    - server
    - config
  roles:
    - k3s-config