---
- name: Restart k3s workers
  hosts: k3s_workers
  gather_facts: true
  become: true
  serial: 1
  vars:
    kube_config_path: /etc/rancher/k3s/k3s.yaml
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
    K8S_AUTH_KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - k3s-restart

- name: Restart k3s managers
  hosts: k3s_managers
  gather_facts: true
  become: true
  serial: 1
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
    K8S_AUTH_KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - k3s-restart
