---
- name: Install Helm
  hosts: k3s_managers
  gather_facts: true
  become: true
  tasks:
    - name: Add Helm GPG Key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm APT Repository
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        update_cache: true

    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: true

    - name: Add users to 'k3s' group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: k3s
        append: true
        state: present
      with_items:
        - ansible
        - devops

    - name: Add export for KUBECONFIG to .bashrc
      ansible.builtin.lineinfile:
        path: /home/{{ item }}/.bashrc
        line: "export KUBECONFIG={{ kube_config_path }}"
      with_items:
        - ansible
        - devops

    - name: Add alias for kubectl to .bashrc
      ansible.builtin.lineinfile:
        path: /home/{{ item }}/.bashrc
        line: "alias k=kubectl"
      with_items:
        - ansible
        - devops
