---
- name: k3s workers
  hosts: 
    - k3s_workers
    - test-k3s-workers
  gather_facts: true
  become: true
  serial: 1
  vars:
    kube_config_path: /etc/rancher/k3s/k3s.yaml
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - k3s-restart

- name: k3 managers
  hosts: 
    - k3s_managers
    - test-k3s-managers
  gather_facts: true
  become: true
  serial: 1
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - k3s-restart
