---
- name: Install Cilium
  hosts: k3s_managers
  become: yes
  gather_facts: true
  tags:
    - cilium
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - cilium

- name: Install MetalLB
  hosts: k3s_managers
  become: yes
  run_once: true
  tags:
    - metallb
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - metallb

- name: Longhorn prereqs
  hosts: k3s
  become: yes
  tags:
    - nfs
    - longhorn
  tasks:
    - name: Install NFS
      ansible.builtin.apt:
        name: nfs-common
        state: present
    - name: Create default multipath.conf
      ansible.builtin.copy:
        dest: /etc/multipath.conf
        content: |
          defaults {
            user_friendly_names yes
          }
          blacklist {
            devnode "^sd[a-z0-9]+"
          }
      register: multipath_conf
    - name: Reload multipathd
      ansible.builtin.systemd:
        name: multipathd
        state: restarted
      when: multipath_conf.changed

- name: Install Longhorn
  hosts: k3s_managers
  run_once: true
  become: yes
  tags:
    - longhorn
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - longhorn

- name: Install cert-manager
  hosts: k3s_managers
  become: yes
  run_once: true
  tags:
    - cert-manager
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - cert-manager

- name: Install Traefik
  hosts: k3s_managers
  become: yes
  run_once: true
  tags:
    - traefik
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - traefik

- name: Install Pi-hole
  hosts: k3s_managers
  become: yes
  run_once: true
  tags:
    - pihole
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - pihole
