---
- name: Patch servers
  hosts:
    - k3s
  gather_facts: true
  become: true
  # serial: 1
  tags:
    - k3s
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Perform safe upgrade
      ansible.builtin.apt:
        upgrade: yes

    - name: Perform auto-remove
      ansible.builtin.apt:
        autoremove: yes
    
    - name: Check if /var/run/reboot-required exists
      ansible.builtin.stat: 
        path: /var/run/reboot-required
      register: reboot_required
    
    - name: Reboot if required
      when: reboot_required.stat.exists
      ansible.builtin.reboot:
        msg: "[ANSIBLE] Rolling restart"
        post_reboot_delay: 60