{
 "title": "Stack Usage",
 "description": "Dashboard with details about Stack usage on the cluster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "stack", "query": "monitoring, devops, uat, home" }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "stack" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"($stack.*)\"}[$__rate_interval]) *100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "description": "Disk space used",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name=~\"($stack.*)\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{name=~\"(monitoring.*|.*cadvisor)\"}[$__rate_interval])",
     "legendFormat": "{{device}} - reads"
    },
    {
     "expr": "- irate(container_fs_writes_bytes_total{name=~\"(monitoring.*|.*cadvisor)\"}[$__rate_interval])",
     "legendFormat": "{{device}} - writes"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"($stack.*)\"}) by (instance)",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"($stack.*)\"}[$__rate_interval])) by (instance)",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{name=~\"($stack.*)\"}[$__rate_interval])) by (instance)",
     "legendFormat": "sent {{device}} "
    }
   ]
  },
  { "title": "Monitoring Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "stack" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"($stack.*)\"}[$__rate_interval])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"($stack.*)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"($stack.*)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"($stack.*)\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"($stack.*)\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Rx FS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,csv) (irate(container_fs_writes_bytes_total{image!=\"\",device!~\"/dev/dm.*\",name=~\"($stack.*)\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Tx FS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,csv) (irate(container_fs_reads_bytes_total{image!=\"\",device!~\"/dev/dm.*\",name=~\"($stack.*)\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\"($stack.*)\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}