---
- name: Create tigera-operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tigera-operator

- name: Update helm chart
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
    state: present

- name: Deploy Calico with helm
  kubernetes.core.helm:
    name: calico
    state: present
    namespace: tigera-operator
    chart_ref: projectcalico/tigera-operator
    values:
      installation:
        enabled: true
        calicoNetwork:
          ipPools:
            - cidr: "{{ cluster_cidr }}"
              encapsulation: VXLAN
          containerIPForwarding: 'Enabled'
        typhaDeployment:
          spec:
            template:
              spec:
                tolerations:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: "Exists"
                    effect: "NoSchedule"
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
      defaultFelixConfiguration:
        enabled: true
        wireguardEnabled: true
        wireguardEnabledV6: true
