---
- name: Check if K3s is already running
  ansible.builtin.systemd:
    name: k3s-agent
  register: k3s_status
  changed_when: false

- name: Create k3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Create k3s config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: 0600

- name: Setup k3s if not running
  when: k3s_status.status != 'running'
  block:
    - name: Install k3s server binaries
      ansible.builtin.command: 
        cmd: /usr/local/bin/k3s-install.sh
      environment: 
        INSTALL_K3S_SKIP_START: "true"
        INSTALL_K3S_EXEC: "agent"
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
      changed_when: true

    - name: Copy k3s agent service file
      register: k3s_agent_service_task
      ansible.builtin.template:
        src: k3s-agent.service.j2
        dest: /etc/systemd/system/k3s-agent.service
        owner: root
        group: root
        mode: 0600

    - name: Enable and check K3s service
      ansible.builtin.systemd:
        name: k3s-agent
        daemon_reload: true
        state: started
        enabled: true