---
- name: Install Loki Helm Charts
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
    state: present

- name: Create temporary values file
  ansible.builtin.tempfile:
    suffix: '.yml'
  register: loki_values_file

- name: Template Loki values file
  ansible.builtin.template:
    src: "templates/values.j2"
    dest: "{{ loki_values_file.path }}"

- name: Install Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    release_namespace: "{{ loki_namespace }}"
    state: present
    values_files:
      - "{{ loki_values_file.path }}"

- name: Install Fluent Bit helm chart
  kubernetes.core.helm_repository:
    name: fluent
    repo_url: https://fluent.github.io/helm-charts
    state: present

- name: Install Fluent Bit
  kubernetes.core.helm:
    name: fluent-bit
    chart_ref: fluent/fluent-bit
    release_namespace: "{{ loki_namespace }}"
    state: present
    values:
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
        requests:
          cpu: 50m
          memory: 32Mi
      config:
        extraFiles:
          label_map.json: |
            {
              "kubernetes": {
                "container_name": "container",
                "namespace_name": "namespace",
                "pod_name": "pod",
                "host": "node",
                "labels": {
                  "app": "app",
                  "app.kubernetes.io/name": "app"
                }
              }
            }
        outputs: |
          [OUTPUT]
              Name                    loki
              Match                   *
              Host                    loki-gateway.monitoring.svc.cluster.local
              port                    80
              tls                     off
              tls.verify              off
              Log_Level               info
              Labels                  agent=fluent-bit
              Label_Map_Path          /fluent-bit/etc/conf/label_map.json
              Remove_Keys             kubernetes
