---
- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true

- name: Restart Keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: true