---
pihole_web_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30643239633437363433623838656565613536363763326536373562333333613262393837306365
  3261613335346333333666363862386535386339306538300a623336623164346166333836636435
  39636264333866393832643334356462376337623934353965656138316266313461393363316234
  3466383063386565390a653934323138633232333032313161653633373062643062313733383662
  3833

pihole_version: '2024.07.0'

pihole_namespace: pihole-system

job_template:
  metadata:
    name: pihole-sync
    namespace: {{ pihole_namespace }}
  spec:
    nodeSelector:
      kubernetes.io/role: worker
    containers:
      - name: sync
        image: mattwebbio/orbital-sync:1
        env:
          - name: PRIMARY_HOST_BASE_URL
            value: 'https://primary-http.{{ pihole_namespace }}.svc.cluster.local'
          - name: PRIMARY_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-secrets
                key: WEBPASSWORD
          - name: SECONDARY_HOSTS_1_BASE_URL
            value: 'http://secondary-http.{{ pihole_namespace }}.svc.cluster.local'
          - name: SECONDARY_HOSTS_1_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-secrets
                key: WEBPASSWORD
          - name: RUN_ONCE
            value: "true"
    restartPolicy: OnFailure
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                  - worker
    resources:
      requests:
        memory: "128Mi"
        cpu: "10m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule