---
- name: Deploy
  when: kubernetes_deploy | default(false)
  block:
    - name: Create tigera-operator namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: tigera-operator

    - name: Update helm chart
      kubernetes.core.helm_repository:
        name: projectcalico
        repo_url: https://docs.tigera.io/calico/charts
        state: present

    - name: Deploy Calico with helm
      kubernetes.core.helm:
        name: calico
        state: present
        namespace: tigera-operator
        chart_ref: projectcalico/tigera-operator
        values:
          installation:
            enabled: true
            cni:
              type: Calico  
              ipam:
                type: Calico
            calicoNetwork:
              ipPools:
                - cidr: 10.42.0.0/16 # TODO: Make this a variable
                  encapsulation: IPIP
                  natOutgoing: 'Enabled'
                  nodeSelector: all()
              containerIPForwarding: 'Enabled'
            controlPlaneNodeSelector:
              node-role.kubernetes.io/control-plane: "true"
            controlPlaneReplicas: 2
            serviceCIDRs:
              - 10.43.0.0/16
          defaultFelixConfiguration:
            enabled: true
            wireguardEnabled: true
            wireguardEnabledV6: true
            # failsafeInboundHostPorts:
            #   - tcp:22 # SSH
            #   - udp:68 # DHCP
            #   - tcp:179 # BGP
            #   - tcp:2379 # etcd
            #   - tcp:2380 # etcd
            #   - udp:4789 # VXLAN
            #   - tcp:5473 # Typha
            #   - tcp:6443 # Kubernetes API
            #   - tcp:6666 # etcd
            #   - tcp:6667 # etcd
            #   - tcp:7946 # MetalLB
            #   - udp:7946 # MetalLB
            #   - udp:51820 # Wireguard IPv4
            #   - udp:51821 # Wireguard IPv6
            # failsafeOutboundHostPorts:
            #   - udp:53 # DNS
            #   - tcp:53 # DNS
            #   - udp:67 # DHCP
            #   - tcp:179 # BGP
            #   - tcp:2379 # etcd
            #   - tcp:2380 # etcd
            #   - udp:4789 # VXLAN
            #   - tcp:5473 # Typha
            #   - tcp:6443 # Kubernetes API
            #   - tcp:6666 # etcd
            #   - tcp:6667 # etcd
            #   - tcp:7946 # MetalLB
            #   - udp:7946 # MetalLB
            #   - udp:51820 # Wireguard IPv4
            #   - udp:51821 # Wireguard IPv6

    - name: Create BGPConfiguration for Service CIDR
      run_once: true
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: projectcalico.org/v3
          kind: BGPConfiguration
          metadata:
            name: default
          spec:
            serviceClusterIPs:
              - cidr: 10.43.0.0/16
  
- name: Firewall
  when: kubernetes_firewall | default(false)
  block:
  - name: Allow Calico Traffic from Kubernetes Nodes
    community.general.ufw:
      rule: allow
      direction: in
      src: "{{ item.src }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      comment: "{{ item.comment }}"
    with_items:
      - src: "{{ k3s_manager_subnet }}"
        port: 179
        proto: 'tcp'
        comment: 'BGP - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 179
        proto: 'tcp'
        comment: 'BGP - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 4789
        proto: 'udp'
        comment: 'VXLAN - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 4789
        proto: 'udp'
        comment: 'VXLAN - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 5473
        proto: 'tcp'
        comment: 'Typha - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 5473
        proto: 'tcp'
        comment: 'Typha - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 51821
        proto: 'udp'
        comment: 'Wireguard IPv6 - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 51821
        proto: 'udp'
        comment: 'Wireguard IPv6 - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 51820
        proto: 'udp'
        comment: 'Wireguard IPv4 - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 51820
        proto: 'udp'
        comment: 'Wireguard IPv4 - Workers'

      