---
- name: Create tigera-operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tigera-operator

- name: Update helm chart
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
    state: present

- name: Deploy Calico with helm
  kubernetes.core.helm:
    name: calico
    state: present
    namespace: tigera-operator
    chart_ref: projectcalico/tigera-operator
    values:
      installation:
        enabled: true
        calicoNetwork:
          ipPools:
            - cidr: "{{ cluster_cidr }}"
          containerIPForwarding: 'Enabled'
      defaultFelixConfiguration:
        enabled: true
        wireguardEnabled: true
        wireguardEnabledV6: true

- name: Create BGP configuration
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: projectcalico.org/v1
      kind: BGPConfiguration
      metadata:
        name: default
      spec:
        serviceClusterIPs:
          - cidr: "{{ service_cidr }}"