---
- name: Deploy
  when: kubernetes_deploy | default(false)
  block:
    - name: Create tigera-operator namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: tigera-operator

    - name: Update helm chart
      kubernetes.core.helm_repository:
        name: projectcalico
        repo_url: https://docs.tigera.io/calico/charts
        state: present

    - name: Deploy Calico with helm
      kubernetes.core.helm:
        name: calico
        state: present
        namespace: tigera-operator
        chart_ref: projectcalico/tigera-operator
        values:
          hostEndpoints:
            - name: lan
              namespace: kube-system
              hosts:
                - "{{ network.identifier }}.{{ networks.subnets.lan }}"
            - name: managers
              namespace: kube-system
              hosts:
                - "{{ k3s_manager_subnet }}"
            - name: workers
              namespace: kube-system
              hosts:
                - "{{ k3s_worker_subnet }}"
          installation:
            enabled: true
            calicoNetwork:
              ipPools:
                - cidr: 10.42.0.0/16 # TODO: Make this a variable
              containerIPForwarding: 'Enabled'
          defaultFelixConfiguration:
            enabled: true
            wireguardEnabled: true
            wireguardEnabledV6: true
  
- name: Firewall
  when: kubernetes_firewall | default(false)
  block:
  - name: Allow Calico Traffic from Kubernetes Nodes
    community.general.ufw:
      rule: allow
      direction: in
      src: "{{ item.src }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      comment: "{{ item.comment }}"
    with_items:
      - src: "{{ k3s_manager_subnet }}"
        port: 179
        proto: 'tcp'
        comment: 'BGP - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 179
        proto: 'tcp'
        comment: 'BGP - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 4789
        proto: 'udp'
        comment: 'VXLAN - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 4789
        proto: 'udp'
        comment: 'VXLAN - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 5473
        proto: 'tcp'
        comment: 'Typha - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 5473
        proto: 'tcp'
        comment: 'Typha - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 51821
        proto: 'udp'
        comment: 'Wireguard IPv6 - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 51821
        proto: 'udp'
        comment: 'Wireguard IPv6 - Workers'
      - src: "{{ k3s_manager_subnet }}"
        port: 51820
        proto: 'udp'
        comment: 'Wireguard IPv4 - Managers'
      - src: "{{ k3s_worker_subnet }}"
        port: 51820
        proto: 'udp'
        comment: 'Wireguard IPv4 - Workers'

      