---
- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"

- name: Create LimitRange
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: traefik-limits
        namespace: "{{ namespace }}"
      spec:
        limits:
          - defaultRequest:
              memory: 128Mi
              cpu: 100m
            default:
              memory: 2Gi
              cpu: 1000m
            max:
              memory: 4Gi
              cpu: 2000m
            min:
              memory: 128Mi
              cpu: 100m
            type: Container

- name: Create Traefik Ingress Certificate
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: traefik-local-wildcard
        namespace: "{{ namespace }}"
      spec:
        secretName: traefik-local-wildcard-tls
        dnsNames:
          - "{{ cluster_domain }}"
          - "{{ local_domain }}"
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
        renewBefore: 720h
        duration: 9480h

- name: Install helm chart
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
    state: present

- name: Deploy Traefik with helm
  kubernetes.core.helm:
    name: traefik
    state: present
    namespace: "{{ namespace }}"
    chart_ref: traefik/traefik
    values:
      additionalArguments:
        - --tcpserverstransport.tls.insecureskipverify
      additionalVolumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: logs
          mountPath: /var/log/traefik          
      deployment:
        replicas: 3
        labels:
          app: traefik
        additionalVolumes:
          - name: localtime
            hostPath:
              path: /etc/localtime
          - name: logs
            emptyDir: {}
      ingressRoute:
        dashboard:
          enabled: true
          entryPoints:
            - websecure
          matchRule: Host(`traefik.{{ cluster_domain }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
        healthcheck:
          enabled: true
          entryPoints:
            - websecure
          matchRule: Host(`traefik.{{ cluster_domain }}`) && PathPrefix(`/ping`)
      updateStrategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
      logs:
        general:
          noColor: true
        access:
          enabled: true
          filePath: /var/log/traefik/access.log
          bufferingSize: 100
          fields:
            headers:
              defaultmode: redact
      nodeSelector:
        kubernetes.io/role: worker
      persistence:
        enabled: true
        accessMode: ReadWriteMany
      ports:
        web:
          redirectTo:
            port: websecure
            permanent: true
      providers:
        kubernetesCRD:
          enabled: true
        kubernetesIngress:
          enabled: true
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 4Gi
      service:
        annotations:
          metallb.universe.tf/allow-shared-ip: traefik
          metallb.universe.tf/loadBalancerIps: "{{ ingress_ip }}"
      tlsStore:
        default:
          defaultCertificate:
            secretName: traefik-local-wildcard-tls         

- name: Create Longhorn Ingress
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: longhorn
        namespace: longhorn-system
        labels:
          app: longhorn-ui
          namespace: longhorn-system
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-prod  
          cert-manager.io/duration: 2160h
          cert-manager.io/renew-before: 360h           
      spec:
        rules:
          - host: longhorn.{{ cluster_domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: longhorn-frontend
                      port:
                        number: 80
          - host: longhorn.local.{{ cluster_domain }}
        tls:
          - hosts:
              - longhorn.{{ cluster_domain }}
              - longhorn.local.{{ cluster_domain }}
            secretName: longhorn-http-proxy-tls