name: Auto Deploy
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: false
        type: choice
        options:
          - test-k3s
          - game-k3s
          - all
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  ###
  ### CLUSTER SETUP
  ###
  haproxy:
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: haproxy
          vars: ""

  prereq:
    needs:
      - haproxy
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: prereq
          vars: ""

  servers:
    needs:
      - prereq
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: init-managers
          vars: ""

  workers:
    needs:
      - servers
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: init-workers
          vars: ""

  ###
  ### MIDDLEWARE
  ###
  cilium:
    needs:
      - workers
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: cilium
          vars: ""

  cluster-config:
    needs:
      - cilium
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: cluster-config
          vars: ""

  metallb:
    needs:
      - cilium
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "METALLB"

  longhorn:
    needs:
      - cilium
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "LONGHORN"

  cert-manager:
    needs:
      - longhorn
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "LONGHORN"

  pihole:
    needs:
      - metallb
      - longhorn
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "PIHOLE"

  traefik:
    needs:
      - cert-manager
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "TRAEFIK"

  ###
  ### MONITORING
  ###
  prometheus:
    needs:
      - traefik
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "PROMETHEUS"

  loki:
    needs:
      - metallb
      - longhorn
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "LOKI"

  grafana:
    needs:
      - prometheus
      - loki
    if: ${{ !failure() }}
    runs-on:
      - self-hosted
      - ansible
    steps:
      - run: echo "GRAFANA"
