# This is a basic workflow to help you get started with Actions

name: k3s cluster middleware

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cluster:
        description: 'The cluster to run the playbook against'
        required: true
        type: choice
        options:
          - test-k3s
          - game-k3s
          - all
      tags:
        description: 'The tags to run'
        type: choice
        options:
          - all
          - calico
          - metallb
          - longhorn
          - cert-manager
          - traefik
          - pihole
      extra_vars:
        description: 'Extra vars to pass to the playbook'
        required: false
        default: ''


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
      - ansible

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster }}
          tags: ${{ github.event.inputs.tags }}
          vars: ${{ github.event.inputs.extra_vars }}